#!/usr/bin/env python3
"""
Integrate flood_section_module.html into interactive_dashboard.html as a full-width card.

- Renames module classes that collide with the dashboard's global CSS (.cg .sv .toggle .kl .kv .ks)
- Drops the module's page-level rules (:root, *, body, .card, h2, .src-badge) — the dashboard already has them
- Scopes every remaining module rule under #floodSectionCard
- Inserts <style>, the <article> card and its <script> right after the "Building Section + Sensitivity" row
- Idempotent: a previous insertion (marked by FLOOD-SECTION-BEGIN/END) is replaced

usage: python3 integrate_flood_section.py flood_section_module.html interactive_dashboard.html [out.html] [--no-fem]
       --no-fem  omit the "Export to FEM" block (Abaqus / DIANA export) from the injected card
"""
import re, sys, shutil, datetime

RENAME = {'cg': 'fcg', 'sv': 'fsv', 'toggle': 'ftog', 'kl': 'fkl', 'kv': 'fkv', 'ks': 'fks', 'sub': 'fsub'}
DROP_PREFIXES = (':root', '*{', 'body{', '.card{', 'h2{', 'h2::before', '.src-badge', '.src-js')
MARK_B, MARK_E = '<!-- FLOOD-SECTION-BEGIN (generated by integrate_flood_section.py) -->', '<!-- FLOOD-SECTION-END -->'


def rename_classes(text):
    for old, new in RENAME.items():
        text = re.sub(r'class="' + old + r'([" ])', 'class="' + new + r'\1', text)           # class="cg" / class="cg id..."
        text = re.sub(r'(class="[^"]*\s)' + old + r'([" ])', r'\1' + new + r'\2', text)       # second class in a list
        text = re.sub(r'(?<![\w-])\.' + old + r'(?![\w-])', '.' + new, text)                # CSS selectors
    return text


def scope_css(css, scope='#floodSectionCard'):
    """Prefix every selector with the scope. Handles one level of @media nesting."""
    out, i = [], 0
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.S).strip()
    while i < len(css):
        if css.startswith('@media', i):
            j = css.index('{', i); depth, k = 1, j + 1
            while depth: depth += {'{': 1, '}': -1}.get(css[k], 0); k += 1
            out.append(css[i:j + 1] + scope_css(css[j + 1:k - 1], scope) + '}')
            i = k
            continue
        if css.startswith('@keyframes', i):
            j = css.index('{', i); depth, k = 1, j + 1
            while depth: depth += {'{': 1, '}': -1}.get(css[k], 0); k += 1
            out.append(css[i:k]); i = k
            continue
        j = css.find('{', i)
        if j < 0: break
        k = css.index('}', j)
        sels, body = css[i:j].strip(), css[j:k + 1]
        if sels and not sels.startswith('/*'):
            if any((sels.replace(' ', '') + '{').startswith(pfx) for pfx in DROP_PREFIXES):
                i = k + 1; continue
            sels = ', '.join(f'{scope} {s.strip()}' for s in sels.split(','))
            out.append(sels + body)
        i = k + 1
    return '\n'.join(out)


def pieces(module_html, fem=True):
    m = rename_classes(module_html)
    if not fem:                                          # strip the "Export to FEM" block and its generators (kept for a later release)
        a = m.index('  <div class="fem" id="femExport">'); b = m.index('  <details class="notes">')
        m = m[:a] + m[b:]
        a = m.index('  function femModel(){'); b = m.index('  window.FLOOD_EXPORT = {femModel, abaqusScript, dianaScript};\n') + len('  window.FLOOD_EXPORT = {femModel, abaqusScript, dianaScript};\n')
        m = m[:a] + m[b:]
        m = re.sub(r'^/\* FEM export \*/\n(?:\.fem[^\n]*\n|\.fbtn[^\n]*\n)+', '', m, flags=re.M)
        m = m.replace('// ── building vertical load and FEM export', '// ── building vertical load (σv)')
        m = re.sub(r"\n    \{ const roof = p\.FFE \+ p\.n\*p\.hs, base = p\.bs \? p\.ELb : p\.Ge; const fls = floorLine\(p\);\n      const fn = \$\('femNote'\)[^\n]*\n", '\n', m)
    css = m[m.index('<style>') + 7:m.index('</style>')]
    article = m[m.index('<article'):m.index('</article>') + 10]
    script = m[m.index('<script>'):m.index('</script>') + 9]
    css = scope_css(css)
    block = '\n'.join([
        MARK_B,
        '<style>', css, '</style>',
        '<div style="margin-bottom:16px">', article, '</div>',
        script,
        MARK_E, ''])
    return block


def integrate(module_path, dash_path, out_path=None, fem=True):
    module = open(module_path, encoding='utf-8').read()
    dash = open(dash_path, encoding='utf-8').read()
    block = pieces(module, fem)
    if MARK_B in dash:                                  # remove a previous insertion (wherever it was)
        dash = dash[:dash.index(MARK_B)] + dash[dash.index(MARK_E) + len(MARK_E):].lstrip('\n')
    # insert right below the title / data-sources card, above the "KPIs below are recomputed…" line
    anchor = '        <p class="sub" style="margin:0 0 8px 4px'
    assert anchor in dash, 'anchor not found'
    dash = dash.replace(anchor, block + anchor, 1)
    out_path = out_path or dash_path
    if out_path == dash_path:
        import os
        bk = dash_path.replace('.html', f'_backup_{datetime.date.today():%Y%m%d}.html')
        if os.path.exists(bk): bk = bk.replace('.html', f'_{datetime.datetime.now():%H%M%S}.html')   # never overwrite an earlier backup
        shutil.copy(dash_path, bk)
    open(out_path, 'w', encoding='utf-8').write(dash)
    return out_path, len(block)


if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    print(integrate(*args[:3], fem='--no-fem' not in sys.argv))
